services:
  - type: web
    name: rental-price-tracker
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: USE_PLAYWRIGHT
        value: "1"
      - key: TEST_MODE_LOCAL
        value: "0"  # Real scraping mode (0=real scraping, 1=test URLs)
      - key: SCRAPER_SERVICE
        value: "scrapeops"
      - key: SCRAPER_API_KEY
        sync: false
      - key: SCRAPER_COUNTRY
        value: "pt"
      - key: TEST_FARO_URL
        sync: false
      - key: TEST_ALBUFEIRA_URL
        sync: false
      - key: TARGET_URL
        sync: false
      - key: CARJET_PRICE_ADJUSTMENT_PCT
        value: "3.12"
      - key: CARJET_PRICE_OFFSET_EUR
        value: "0"
